(defcustom rsta-lang-list
    (list "."
        "0815"
        "360_Assembly"
        "4D"
        "4DOS_Batch"
        "6502_Assembly"
        "6800_Assembly"
        "68000_Assembly"
        "8_1/2"
        "80386_Assembly"
        "8051_Assembly"
        "8080_Assembly"
        "8086_Assembly"
        "8th"
        "A+"
        "ABAP"
        "ACL2"
        "Action!"
        "ActionScript"
        "Ada"
        "Agda"
        "Agda2"
        "Agena"
        "Aikido"
        "Aime"
        "Algae"
        "ALGOL"
        "ALGOL_60"
        "ALGOL_68"
        "ALGOL_W"
        "ALGOL-M"
        "Alice_ML"
        "Alore"
        "AmbientTalk"
        "AmigaE"
        "AMPL"
        "AngelScript"
        "ANT"
        "AntLang"
        "ANTLR"
        "Anyways"
        "Apex"
        "APL"
        "App_Inventor"
        "AppleScript"
        "Applesoft_BASIC"
        "Application_Master"
        "Apricot"
        "Arbre"
        "Arc"
        "Arendelle"
        "Argile"
        "ARM_Assembly"
        "ArnoldC"
        "AsciiDots"
        "ASP"
        "ASP.Net"
        "AspectC++"
        "AspectJ"
        "Assembly"
        "Astro"
        "Asymptote"
        "ATS"
        "AutoHotkey"
        "AutoIt"
        "AutoLISP"
        "AWK"
        "Axe"
        "Axiom"
        "Axum"
        "B"
        "B4J"
        "Babel"
        "BaCon"
        "BASIC"
        "Basic_Casio"
        "BASIC256"
        "Batch_File"
        "Battlestar"
        "BBC_BASIC"
        "Bc"
        "BCPL"
        "Beeswax"
        "Befunge"
        "Beta"
        "Biferno"
        "Binary_Lambda_Calculus"
        "Blast"
        "BlitzMax"
        "Blz"
        "BML"
        "Boo"
        "Bori"
        "Brace"
        "Bracmat"
        "Brainf***"
        "Brat"
        "Brlcad"
        "Burlesque"
        "C"
        "C_sharp"
        "C_Shell"
        "C++"
        "C++/CLI"
        "C0H"
        "C1R"
        "Cach%C3%A9_ObjectScript"
        "CafeOBJ"
        "Caml"
        "Cat"
        "CB80"
        "Cduce"
        "Cecil"
        "Ceylon"
        "Chapel"
        "Chef"
        "CHR"
        "ChucK"
        "Cilk"
        "Cilk++"
        "Clarion"
        "Clay"
        "Clean"
        "Clipper"
        "Clipper/XBase++"
        "CLIPS"
        "Clojure"
        "CMake"
        "COBOL"
        "Cobra"
        "Coco"
        "CoffeeScript"
        "ColdFusion"
        "Comal"
        "Comefrom0x10"
        "Commodore_BASIC"
        "Common_Lisp"
        "Component_Pascal"
        "Computer/zero_Assembly"
        "Coq"
        "Crack"
        "Crystal"
        "Cubescript"
        "Curry"
        "D"
        "Dafny"
        "Dao"
        "Dart"
        "Datalog"
        "Dc"
        "DCL"
        "DDNC"
        "Delphi"
        "Deluge"
        "DeviousYarn"
        "Diesel"
        "DIV_Games_Studio"
        "DM"
        "DMS"
        "Dodo0"
        "DUP"
        "DWScript"
        "Dylan"
        "Dylan.NET"
        "D%C3%A9j%C3%A0_Vu"
        "E"
        "EC"
        "EchoLisp"
        "ECL"
        "EDSAC_order_code"
        "Eero"
        "Efene"
        "Egel"
        "Egison"
        "EGL"
        "EhBASIC"
        "Eiffel"
        "Ela"
        "Elan"
        "ElastiC"
        "Elena"
        "Elisa"
        "Elixir"
        "ELLA"
        "Elm"
        "Emacs_Lisp"
        "Emojicode"
        "Epigram"
        "Erlang"
        "ERRE"
        "Es"
        "ESQL"
        "Euler"
        "Euphoria"
        "Ezhil"
        "F"
        "F_Sharp"
        "Factor"
        "Falcon"
        "FALSE"
        "Fan"
        "Fancy"
        "Fantom"
        "FAUST"
        "FBSL"
        "FeatureC++"
        "Felix"
        "Ferite"
        "Fexl"
        "Fish"
        "FLORA-2"
        "Florid"
        "FOCAL"
        "FormulaOne"
        "Forth"
        "Fortran"
        "Fortress"
        "FP"
        "FPI"
        "Free_Pascal"
        "FreeBASIC"
        "FreeMat"
        "Frege"
        "Friendly_interactive_shell"
        "Frink"
        "FRISC_Assembly"
        "FunL"
        "Futhark"
        "FutureBasic"
        "FUZE_BASIC"
        "F%C5%8Drmul%C3%A6"
        "Gambas"
        "GAP"
        "Gastona"
        "Gecho"
        "Gema"
        "Gentee"
        "Genyris"
        "GEORGE"
        "GFA_Basic"
        "Glagol"
        "GLBasic"
        "Glee"
        "GlovePIE"
        "GLSL"
        "GML"
        "Gnuplot"
        "Go"
        "Go!"
        "Golfscript"
        "Golo"
        "Goo"
        "Gosu"
        "Gri"
        "Groovy"
        "GUISS"
        "GW-BASIC"
        "Hack"
        "Halon"
        "Harbour"
        "Haskell"
        "Haxe"
        "Heron"
        "HicEst"
        "HLA"
        "HolyC"
        "Hoon"
        "Hope"
        "HPPPL"
        "HQ9+"
        "Huginn"
        "Hy"
        "HyperTalk"
        "I"
        "Icon"
        "IDL"
        "Idris"
        "Inform_6"
        "Inform_7"
        "Informix_4GL"
        "Integer_BASIC"
        "Intercal"
        "Io"
        "Ioke"
        "Iptscrae"
        "IS-BASIC"
        "IWBASIC"
        "J"
        "Jabaco"
        "Jack"
        "Jacquard_Loom"
        "JAMES_II/Rule-based_Cellular_Automata"
        "Java"
        "JavaFX_Script"
        "JavaScript"
        "JCL"
        "JoCaml"
        "JOVIAL"
        "Joy"
        "Jq"
        "JScript.NET"
        "JudoScript"
        "Julia"
        "K"
        "Kabap"
        "Kamailio_Script"
        "Kaya"
        "KeyList_Databasing"
        "Kite"
        "Kitten"
        "Klong"
        "KonsolScript"
        "Kotlin"
        "L++"
        "L.in.oleum"
        "LabVIEW"
        "Lambda_Prolog"
        "Lambdatalk"
        "Lang5"
        "Lasso"
        "LaTeX"
        "LC2200_Assembly"
        "LC3_Assembly"
        "Leon"
        "LFE"
        "Lhogho"
        "Liberty_BASIC"
        "LibreOffice_Basic"
        "Lily"
        "Lilypond"
        "Limbo"
        "Lingo"
        "Lisaac"
        "Lisp"
        "LiveCode"
        "Livecode"
        "LiveScript"
        "LLP"
        "LLVM"
        "Lobster"
        "Locomotive_Basic"
        "Loglan82"
        "Logo"
        "Logtalk"
        "LOLCODE"
        "Lolli"
        "Lotus_123_Macro_Scripting"
        "LotusScript"
        "Lout"
        "LSE64"
        "LSL"
        "Lua"
        "Lucid"
        "Luck"
        "Luna"
        "Lush"
        "Lygon"
        "M2000_Interpreter"
        "M4"
        "M680x0"
        "Make"
        "Malbolge"
        "Maple"
        "MAPPER"
        "MathCortex"
        "Mathematica"
        "Mathprog"
        "MATLAB"
        "Maude"
        "Maxima"
        "MAXScript"
        "MBS"
        "MDL"
        "ME10_macro"
        "MEL"
        "Mercury"
        "Metafont"
        "Metapost"
        "MGS"
        "Microsoft_Small_Basic"
        "MINIL"
        "MIPS_Assembly"
        "Mirah"
        "MIRC_Scripting_Language"
        "Mirelle"
        "ML"
        "ML/I"
        "MLite"
        "MMIX"
        "Modula-2"
        "Modula-3"
        "Mond"
        "Monicelli"
        "Monkey"
        "Monte"
        "MontiLang"
        "MOO"
        "MoonScript"
        "Morfa"
        "MSX_Basic"
        "MUF"
        "MUMPS"
        "Myrddin"
        "MyrtleScript"
        "MySQL"
        "Mython"
        "Mythryl"
        "N/t/roff"
        "NASL"
        "Neat"
        "Neko"
        "Nemerle"
        "NESL"
        "NetLogo"
        "NetRexx"
        "NewLISP"
        "NewtonScript"
        "NGS"
        "Nial"
        "Nice"
        "Nickle"
        "Nim"
        "Nit"
        "Niue"
        "Nix"
        "NQP"
        "NSIS"
        "OASYS"
        "OASYS_Assembler"
        "Oberon-2"
        "Objeck"
        "Object_Pascal"
        "ObjectIcon"
        "Objective-C"
        "OCaml"
        "Occam"
        "Octave"
        "Oforth"
        "Ol"
        "Omega"
        "Onyx"
        "OOC"
        "OOCalc"
        "OoRexx"
        "Opa"
        "OpenC++"
        "OpenEdge/Progress"
        "OpenLisp"
        "Openscad"
        "OPL"
        "Order"
        "OxygenBasic"
        "Oxygene"
        "Oz"
        "Panda"
        "Panoramic"
        "Pare"
        "PARI/GP"
        "Pascal"
        "PASM"
        "PDP-11_Assembly"
        "Peloton"
        "Pentium_Assembly"
        "PeopleCode"
        "Perl"
        "Perl_6"
        "Perl5i"
        "Phix"
        "PHL"
        "PHP"
        "Picat"
        "PicoLisp"
        "Pict"
        "Piet"
        "Pike"
        "PILOT"
        "PIR"
        "PL/B"
        "PL/I"
        "PL/M"
        "PL/pgSQL"
        "PL/SQL"
        "PlainTeX"
        "Plan"
        "PLUS"
        "PLZ/SYS"
        "Pony"
        "Pop11"
        "PostScript"
        "Potion"
        "POV-Ray"
        "PowerBASIC"
        "Powerbuilder"
        "PowerShell"
        "PPC_Assembly"
        "PPL"
        "Processing"
        "ProDOS"
        "Prolog"
        "PSQL"
        "Pure"
        "Pure_Data"
        "PureBasic"
        "Purity"
        "Pyret"
        "Python"
        "Q"
        "QBasic"
        "Qi"
        "Qore"
        "QuakeC"
        "Quill"
        "Quite_BASIC"
        "R"
        "Ra"
        "Racket"
        "RapidQ"
        "Rapira"
        "Rascal"
        "Raven"
        "REALbasic"
        "Reason"
        "REBOL"
        "Red"
        "Reduce"
        "Refal"
        "Retro"
        "REXX"
        "Rhope"
        "Ring"
        "RLaB"
        "RLSL"
        "Robotic"
        "RPG"
        "RPGIV"
        "RPL"
        "RPL/2"
        "RTL/2"
        "RTSL"
        "Ruby"
        "Rubylog"
        "Run_BASIC"
        "Rust"
        "S-lang"
        "Sage"
        "Salmon"
        "SAS"
        "SASL"
        "Sass/SCSS"
        "Sather"
        "Scala"
        "Scheme"
        "Scilab"
        "Scratch"
        "Script_Basic"
        "Script3D"
        "ScriptBasic"
        "Sed"
        "Seed7"
        "Self"
        "SequenceL"
        "Set_lang"
        "SETL"
        "Setl4"
        "SheerPower_4GL"
        "Shen"
        "Shiny"
        "Sidef"
        "SimpleLang"
        "SIMPOL"
        "Simula"
        "Sinclair_ZX81_BASIC"
        "Sisal"
        "SkookumScript"
        "Slate"
        "Smalltalk"
        "Smart_BASIC"
        "SMEQL"
        "SmileBASIC"
        "Snobol"
        "SNOBOL4"
        "SNUSP"
        "Soar"
        "SoneKing_Assembly"
        "SPAD"
        "SPARC_Assembly"
        "SPARK"
        "Sparkling"
        "Spin"
        "SPL"
        "SQL"
        "SQL_PL"
        "Squirrel"
        "SSEM"
        "Standard_ML"
        "Star"
        "Stata"
        "StreamIt"
        "Suneido"
        "Superbase_BASIC"
        "SuperCollider"
        "Supernova"
        "SuperTalk"
        "Swift"
        "Symsyn"
        "SystemVerilog"
        "TAL"
        "Tbas"
        "Tcl"
        "TechBASIC"
        "Teco"
        "TeLa"
        "Terra"
        "TestML"
        "Thistle"
        "Thyrd"
        "TI-83_BASIC"
        "TI-83_Hex_Assembly"
        "TI-89_BASIC"
        "TIScript"
        "ToffeeScript"
        "Toka"
        "TorqueScript"
        "TPP"
        "Transact-SQL"
        "TransFORTH"
        "Trith"
        "True_BASIC"
        "TSE_SAL"
        "Turing"
        "TUSCRIPT"
        "Twelf"
        "TXR"
        "TypeScript"
        "UC++"
        "Unicon"
        "Uniface"
        "UNIX_Shell"
        "UnixPipes"
        "Unlambda"
        "Ursa"
        "Ursala"
        "UScript"
        "UserRPL"
        "UTFool"
        "V"
        "Vala"
        "VAX_Assembly"
        "VB6"
        "VBA"
        "VBScript"
        "Vedit_macro_language"
        "Verbexx"
        "Verilog"
        "VHDL"
        "Vim_Script"
        "Visual_Basic"
        "Visual_Basic_.NET"
        "Visual_FoxPro"
        "Visual_Objects"
        "Visual_Prolog"
        "Viua_VM_assembly"
        "Vorpal"
        "Vox"
        "VRML"
        "Wart"
        "WDTE"
        "WebAssembly"
        "Whenever"
        "Whitespace"
        "WML"
        "Wolfram_Language"
        "Wollok"
        "Wortel"
        "Wrapl"
        "Wren"
        "X10"
        "X86_64_Assembly"
        "X86_Assembly"
        "Xanadu"
        "XBase"
        "XEec"
        "XL"
        "XLISP"
        "Xojo"
        "XPath_2.0"
        "XPL0"
        "XProc"
        "XQuery"
        "XS"
        "XSLT"
        "XSLT_1.0"
        "XSLT_2.0"
        "XTalk"
        "XUL"
        "Ya"
        "Yabasic"
        "Yacas"
        "Yorick"
        "Z80_Assembly"
        "ZED"
        "Zkl"
        "Zonnon"
        "ZPL"
        "ZX_Spectrum_Basic"
        "%CE%9C"
        "%CE%9CC++") 
  "The initial scrape of rosetta code for clojure.")


 


(defcustom rsta-task-list
  (list "100 doors" 
        "15 Puzzle Game" 
        "15 puzzle solver" 
        "2048" 
        "24 game" 
        "24 game/Solve" 
        "4-rings or 4-squares puzzle" 
        "9 billion names of God the integer" 
        "99 Bottles of Beer" 
        "A+B" 
        "Abbreviations, automatic" 
        "Abbreviations, easy" 
        "Abbreviations, simple" 
        "ABC Problem" 
        "Abstract type" 
        "Abundant, deficient and perfect number classifications" 
        "Accumulator factory" 
        "Ackermann function" 
        "Active Directory/Connect" 
        "Active Directory/Search for a user" 
        "Active object" 
        "Add a variable to a class instance at runtime" 
        "Address of a variable" 
        "AKS test for primes" 
        "Align columns" 
        "Aliquot sequence classifications" 
        "Almost prime" 
        "Amb" 
        "Amicable pairs" 
        "Anagrams" 
        "Anagrams/Deranged anagrams" 
        "Angle difference between two bearings" 
        "Animate a pendulum" 
        "Animation" 
        "Anonymous recursion" 
        "Append a record to the end of a text file" 
        "Apply a callback to an array" 
        "Apply a digital filter (direct form II transposed)" 
        "Arbitrary-precision integers (included)" 
        "Archimedean spiral" 
        "Arena storage pool" 
        "Arithmetic evaluation" 
        "Arithmetic-geometric mean" 
        "Arithmetic-geometric mean/Calculate Pi" 
        "Arithmetic/Complex" 
        "Arithmetic/Integer" 
        "Arithmetic/Rational" 
        "Array concatenation" 
        "Array length" 
        "Arrays" 
        "Assertions" 
        "Associative array/Creation" 
        "Associative array/Iteration" 
        "Atomic updates" 
        "Average loop length" 
        "Averages/Arithmetic mean" 
        "Averages/Mean angle" 
        "Averages/Mean time of day" 
        "Averages/Median" 
        "Averages/Mode" 
        "Averages/Pythagorean means" 
        "Averages/Root mean square" 
        "Averages/Simple moving average" 
        "AVL tree" 
        "Babbage problem" 
        "Balanced brackets" 
        "Balanced ternary" 
        "Barnsley fern" 
        "Benford's law" 
        "Bernoulli numbers" 
        "Best shuffle" 
        "Binary digits" 
        "Binary search" 
        "Binary strings" 
        "Bitcoin/address validation" 
        "Bitcoin/public point to address" 
        "Bitmap" 
        "Bitmap/Bresenham's line algorithm" 
        "Bitmap/Bézier curves/Cubic" 
        "Bitmap/Bézier curves/Quadratic" 
        "Bitmap/Flood fill" 
        "Bitmap/Histogram" 
        "Bitmap/Midpoint circle algorithm" 
        "Bitmap/PPM conversion through a pipe" 
        "Bitmap/Read a PPM file" 
        "Bitmap/Read an image through a pipe" 
        "Bitmap/Write a PPM file" 
        "Bitwise IO" 
        "Bitwise operations" 
        "Boolean values" 
        "Box the compass" 
        "Brace expansion" 
        "Break OO privacy" 
        "Brownian tree" 
        "Bulls and cows" 
        "Bulls and cows/Player" 
        "Caesar cipher" 
        "Calculating the value of e" 
        "Calendar" 
        "Calendar - for \"REAL\" programmers" 
        "Call a foreign-language function" 
        "Call a function" 
        "Call a function in a shared library" 
        "Call an object method" 
        "Canny edge detector" 
        "Carmichael 3 strong pseudoprimes" 
        "Cartesian product of two or more lists" 
        "Case-sensitivity of identifiers" 
        "Casting out nines" 
        "Catalan numbers" 
        "Catalan numbers/Pascal's triangle" 
        "Catamorphism" 
        "Catmull–Clark subdivision surface" 
        "Chaos game" 
        "Character codes" 
        "Chat server" 
        "Check Machin-like formulas" 
        "Check that file exists" 
        "Checkpoint synchronization" 
        "Chinese remainder theorem" 
        "Chinese zodiac" 
        "Cholesky decomposition" 
        "Church Numerals" 
        "Circles of given radius through two points" 
        "Classes" 
        "Closest-pair problem" 
        "Closures/Value capture" 
        "Collections" 
        "Color of a screen pixel" 
        "Color quantization" 
        "Colour bars/Display" 
        "Colour pinstripe/Display" 
        "Colour pinstripe/Printer" 
        "Combinations" 
        "Combinations and permutations" 
        "Combinations with repetitions" 
        "Comma quibbling" 
        "Command-line arguments" 
        "Commatizing numbers" 
        "Comments" 
        "Compare a list of strings" 
        "Compare sorting algorithms' performance" 
        "Compile-time calculation" 
        "Compiler/AST interpreter" 
        "Compiler/code generator" 
        "Compiler/lexical analyzer" 
        "Compiler/syntax analyzer" 
        "Compiler/virtual machine interpreter" 
        "Compound data type" 
        "Concurrent computing" 
        "Conditional structures" 
        "Conjugate transpose" 
        "Constrained genericity" 
        "Constrained random points on a circle" 
        "Continued fraction" 
        "Continued fraction/Arithmetic/Construct from rational number" 
        "Convert decimal number to rational" 
        "Convert seconds to compound duration" 
        "Conway's Game of Life" 
        "Copy a string" 
        "Count in factors" 
        "Count in octal" 
        "Count occurrences of a substring" 
        "Count the coins" 
        "Cramer's rule" 
        "CRC-32" 
        "Create a file" 
        "Create a file on magnetic tape" 
        "Create a two-dimensional array at runtime" 
        "Create an HTML table" 
        "Create an object at a given address" 
        "CSV data manipulation" 
        "CSV to HTML translation" 
        "Cumulative standard deviation" 
        "Currency" 
        "Currying" 
        "CUSIP" 
        "Cut a rectangle" 
        "Date format" 
        "Date manipulation" 
        "Day of the week" 
        "Deal cards for FreeCell" 
        "Death Star" 
        "Deconvolution/1D" 
        "Deconvolution/2D+" 
        "Deepcopy" 
        "Define a primitive data type" 
        "Delegates" 
        "Delete a file" 
        "Department Numbers" 
        "Detect division by zero" 
        "Determine if a string is numeric" 
        "Determine if only one instance is running" 
        "Digital root" 
        "Digital root/Multiplicative digital root" 
        "Dijkstra's algorithm" 
        "Dinesman's multiple-dwelling problem" 
        "Dining philosophers" 
        "Discordian date" 
        "Distributed programming" 
        "DNS query" 
        "Documentation" 
        "Dot product" 
        "Doubly-linked list/Definition" 
        "Doubly-linked list/Element definition" 
        "Doubly-linked list/Element insertion" 
        "Doubly-linked list/Traversal" 
        "Dragon curve" 
        "Draw a clock" 
        "Draw a cuboid" 
        "Draw a pixel" 
        "Draw a rotating cube" 
        "Draw a sphere" 
        "Dutch national flag problem" 
        "Dynamic variable names" 
        "Echo server" 
        "Eertree" 
        "Egyptian division" 
        "Egyptian fractions" 
        "EKG sequence convergence" 
        "Element-wise operations" 
        "Elementary cellular automaton" 
        "Emirp primes" 
        "Empty directory" 
        "Empty program" 
        "Empty string" 
        "Enforced immutability" 
        "Entropy" 
        "Entropy/Narcissist" 
        "Enumerations" 
        "Environment variables" 
        "Equilibrium index" 
        "Ethiopian multiplication" 
        "Euler method" 
        "Euler's identity" 
        "Euler's sum of powers conjecture" 
        "Evaluate binomial coefficients" 
        "Even or odd" 
        "Events" 
        "Evolutionary algorithm" 
        "Exceptions" 
        "Exceptions/Catch an exception thrown in a nested call" 
        "Executable library" 
        "Execute a Markov algorithm" 
        "Execute a system command" 
        "Execute Brain****" 
        "Execute HQ9+" 
        "Execute SNUSP" 
        "Exponentiation operator" 
        "Exponentiation order" 
        "Extend your language" 
        "Extensible prime generator" 
        "Extreme floating point values" 
        "Factorial" 
        "Factors of a Mersenne number" 
        "Factors of an integer" 
        "Farey sequence" 
        "Fast Fourier transform" 
        "FASTA format" 
        "Fibonacci n-step number sequences" 
        "Fibonacci sequence" 
        "Fibonacci word" 
        "Fibonacci word/fractal" 
        "File input/output" 
        "File modification time" 
        "File size" 
        "Filter" 
        "Find common directory path" 
        "Find largest left truncatable prime in a given base" 
        "Find limit of recursion" 
        "Find palindromic numbers in both binary and ternary bases" 
        "Find the intersection of two lines" 
        "Find the last Sunday of each month" 
        "Find the missing permutation" 
        "First class environments" 
        "First-class functions" 
        "First-class functions/Use numbers analogously" 
        "Five weekends" 
        "Fixed length records" 
        "FizzBuzz" 
        "Flatten a list" 
        "Flipping bits game" 
        "Flow-control structures" 
        "Floyd's triangle" 
        "Floyd-Warshall algorithm" 
        "Forest fire" 
        "Fork" 
        "Formal power series" 
        "Formatted numeric output" 
        "Forward difference" 
        "Four bit adder" 
        "Four is magic" 
        "Four is the number of letters in the ..." 
        "Fractal tree" 
        "Fractran" 
        "FTP" 
        "Function composition" 
        "Function definition" 
        "Function frequency" 
        "Function prototype" 
        "Galton box animation" 
        "Gamma function" 
        "Gaussian elimination" 
        "General FizzBuzz" 
        "Generate Chess960 starting position" 
        "Generate lower case ASCII alphabet" 
        "Generate random chess position" 
        "Generator/Exponential" 
        "Generic swap" 
        "Get system command output" 
        "Globally replace text in several files" 
        "Go Fish" 
        "Gray code" 
        "Grayscale image" 
        "Greatest common divisor" 
        "Greatest element of a list" 
        "Greatest subsequential sum" 
        "Greyscale bars/Display" 
        "Guess the number" 
        "Guess the number/With feedback" 
        "Guess the number/With feedback (player)" 
        "GUI component interaction" 
        "GUI enabling/disabling of controls" 
        "GUI/Maximum window dimensions" 
        "Hailstone sequence" 
        "Hamming numbers" 
        "Handle a signal" 
        "Happy numbers" 
        "Harshad or Niven series" 
        "Hash from two arrays" 
        "Hash join" 
        "Haversine formula" 
        "Hello world/Graphical" 
        "Hello world/Line printer" 
        "Hello world/Newbie" 
        "Hello world/Newline omission" 
        "Hello world/Standard error" 
        "Hello world/Text" 
        "Hello world/Web server" 
        "Here document" 
        "Heronian triangles" 
        "Hickerson series of almost integers" 
        "Higher-order functions" 
        "History variables" 
        "Hofstadter Figure-Figure sequences" 
        "Hofstadter Q sequence" 
        "Hofstadter-Conway $10,000 sequence" 
        "Holidays related to Easter" 
        "Honeycombs" 
        "Horizontal sundial calculations" 
        "Horner's rule for polynomial evaluation" 
        "Host introspection" 
        "Hostname" 
        "Hough transform" 
        "HTTP" 
        "HTTPS" 
        "HTTPS/Authenticated" 
        "HTTPS/Client-authenticated" 
        "Huffman coding" 
        "Hunt The Wumpus" 
        "I before E except after C" 
        "IBAN" 
        "Identity matrix" 
        "Idiomatically determine all the characters that can be used for symbols" 
        "Idiomatically determine all the lowercase and uppercase letters" 
        "Image convolution" 
        "Image noise" 
        "Include a file" 
        "Increment a numerical string" 
        "Index finite lists of positive integers" 
        "Infinity" 
        "Inheritance/Multiple" 
        "Inheritance/Single" 
        "Input loop" 
        "Integer comparison" 
        "Integer overflow" 
        "Integer sequence" 
        "Interactive programming" 
        "Introspection" 
        "Inverted index" 
        "Inverted syntax" 
        "Iterated digits squaring" 
        "Jaro distance" 
        "Jensen's Device" 
        "Jewels and Stones" 
        "JortSort" 
        "Josephus problem" 
        "Joystick position" 
        "JSON" 
        "Julia set" 
        "Jump anywhere" 
        "K-d tree" 
        "K-means++ clustering" 
        "Kaprekar numbers" 
        "Kernighans large earthquake problem" 
        "Keyboard input/Flush the keyboard buffer" 
        "Keyboard input/Keypress check" 
        "Keyboard input/Obtain a Y or N response" 
        "Keyboard macros" 
        "Knapsack problem/0-1" 
        "Knapsack problem/Bounded" 
        "Knapsack problem/Continuous" 
        "Knapsack problem/Unbounded" 
        "Knight's tour" 
        "Knuth shuffle" 
        "Knuth's algorithm S" 
        "Knuth's power tree" 
        "Kolakoski sequence" 
        "Kronecker product" 
        "Kronecker product based fractals" 
        "Langton's ant" 
        "Largest int from concatenated ints" 
        "Largest number divisible by its digits" 
        "Last Friday of each month" 
        "Last letter-first letter" 
        "Law of cosines - triples" 
        "Leap year" 
        "Least common multiple" 
        "Left factorials" 
        "Leonardo numbers" 
        "Letter frequency" 
        "Levenshtein distance" 
        "Linear congruential generator" 
        "List comprehensions" 
        "Literals/Floating point" 
        "Literals/Integer" 
        "Literals/String" 
        "Logical operations" 
        "Long multiplication" 
        "Long primes" 
        "Longest common subsequence" 
        "Longest increasing subsequence" 
        "Longest string challenge" 
        "Look-and-say sequence" 
        "Loop over multiple arrays simultaneously" 
        "Loops/Break" 
        "Loops/Continue" 
        "Loops/Do-while" 
        "Loops/Downward for" 
        "Loops/For" 
        "Loops/For with a specified step" 
        "Loops/Foreach" 
        "Loops/Increment loop index within loop body" 
        "Loops/Infinite" 
        "Loops/N plus one half" 
        "Loops/Nested" 
        "Loops/While" 
        "Loops/with multiple ranges" 
        "Loops/Wrong ranges" 
        "LU decomposition" 
        "Lucas-Lehmer test" 
        "Lucky and even lucky numbers" 
        "Ludic numbers" 
        "Luhn test of credit card numbers" 
        "Lychrel numbers" 
        "LZW compression" 
        "MAC Vendor Lookup" 
        "Machine code" 
        "Mad Libs" 
        "Magic squares of doubly even order" 
        "Magic squares of odd order" 
        "Magic squares of singly even order" 
        "Main step of GOST 28147-89" 
        "Make directory path" 
        "Man or boy test" 
        "Mandelbrot set" 
        "Map range" 
        "Matrix arithmetic" 
        "Matrix multiplication" 
        "Matrix transposition" 
        "Matrix-exponentiation operator" 
        "Maximum triangle path sum" 
        "Maze generation" 
        "Maze solving" 
        "McNuggets Problem" 
        "MD4" 
        "MD5" 
        "MD5/Implementation" 
        "Median filter" 
        "Memory allocation" 
        "Memory layout of a data structure" 
        "Menu" 
        "Metaprogramming" 
        "Metered concurrency" 
        "Metronome" 
        "Middle three digits" 
        "Miller–Rabin primality test" 
        "Mind boggling card trick" 
        "Minesweeper game" 
        "Modular exponentiation" 
        "Modular inverse" 
        "Monte Carlo methods" 
        "Monty Hall problem" 
        "Morse code" 
        "Mouse position" 
        "Move-to-front algorithm" 
        "Multifactorial" 
        "Multiple distinct objects" 
        "Multiple regression" 
        "Multiplication tables" 
        "Multiplicative order" 
        "Multisplit" 
        "Munchausen numbers" 
        "Munching squares" 
        "Mutual recursion" 
        "N'th" 
        "N-queens problem" 
        "Named parameters" 
        "Naming conventions" 
        "Narcissist" 
        "Narcissistic decimal number" 
        "Natural sorting" 
        "Nautical bell" 
        "Negative base numbers" 
        "Nested function" 
        "Nested templated data" 
        "Non-continuous subsequences" 
        "Non-decimal radices/Convert" 
        "Non-decimal radices/Input" 
        "Non-decimal radices/Output" 
        "Nonoblock" 
        "Nonogram solver" 
        "Nth root" 
        "Null object" 
        "Number names" 
        "Number reversal game" 
        "Numeric error propagation" 
        "Numerical integration" 
        "Numerical integration/Gauss-Legendre Quadrature" 
        "Object serialization" 
        "Odd word problem" 
        "Old lady swallowed a fly" 
        "OLE Automation" 
        "One of n lines in a file" 
        "One-dimensional cellular automata" 
        "OpenGL" 
        "OpenWebNet Password" 
        "Operator precedence" 
        "Optional parameters" 
        "Order disjoint list items" 
        "Order two numerical lists" 
        "Ordered Partitions" 
        "Ordered words" 
        "Palindrome detection" 
        "Pangram checker" 
        "Paraffins" 
        "Parallel Brute Force" 
        "Parallel calculations" 
        "Parametric polymorphism" 
        "Parametrized SQL statement" 
        "Parse an IP Address" 
        "Parsing/RPN calculator algorithm" 
        "Parsing/RPN to infix conversion" 
        "Parsing/Shunting-yard algorithm" 
        "Partial function application" 
        "Partition an integer X into N primes" 
        "Pascal matrix generation" 
        "Pascal's triangle" 
        "Pascal's triangle/Puzzle" 
        "Password generator" 
        "Pathological floating point problems" 
        "Pattern matching" 
        "Penney's game" 
        "Pentagram" 
        "Percentage difference between images" 
        "Percolation/Bond percolation" 
        "Percolation/Mean cluster density" 
        "Percolation/Mean run density" 
        "Percolation/Site percolation" 
        "Perfect numbers" 
        "Perfect shuffle" 
        "Permutation test" 
        "Permutations" 
        "Permutations by swapping" 
        "Permutations/Derangements" 
        "Permutations/Rank of a permutation" 
        "Pernicious numbers" 
        "Phrase reversals" 
        "Pi" 
        "Pick random element" 
        "Pig the dice game" 
        "Pig the dice game/Player" 
        "Pinstripe/Display" 
        "Pinstripe/Printer" 
        "Plasma effect" 
        "Play recorded sounds" 
        "Playing cards" 
        "Plot coordinate pairs" 
        "Pointers and references" 
        "Poker hand analyser" 
        "Polymorphic copy" 
        "Polymorphism" 
        "Polynomial long division" 
        "Polynomial regression" 
        "Polyspiral" 
        "Population count" 
        "Power set" 
        "Pragmatic directives" 
        "Price fraction" 
        "Primality by trial division" 
        "Prime decomposition" 
        "Primes - allocate descendants to their ancestors" 
        "Primorial numbers" 
        "Priority queue" 
        "Probabilistic choice" 
        "Problem of Apollonius" 
        "Program name" 
        "Program termination" 
        "Proper divisors" 
        "Pythagoras tree" 
        "Pythagorean quadruples" 
        "Pythagorean triples" 
        "QR decomposition" 
        "Quaternion type" 
        "Queue/Definition" 
        "Queue/Usage" 
        "Quickselect algorithm" 
        "Quine" 
        "Ramer-Douglas-Peucker line simplification" 
        "Random number generator (device)" 
        "Random number generator (included)" 
        "Random numbers" 
        "Range expansion" 
        "Range extraction" 
        "Ranking methods" 
        "Rate counter" 
        "Ray-casting algorithm" 
        "RCRPG" 
        "Read a configuration file" 
        "Read a file line by line" 
        "Read a specific line from a file" 
        "Read entire file" 
        "Real constants and functions" 
        "Recaman's sequence" 
        "Record sound" 
        "Reduced row echelon form" 
        "Reflection/Get source" 
        "Reflection/List methods" 
        "Reflection/List properties" 
        "Regular expressions" 
        "Remove duplicate elements" 
        "Remove lines from a file" 
        "Rename a file" 
        "Rendezvous" 
        "Rep-string" 
        "Repeat a string" 
        "Resistor mesh" 
        "Respond to an unknown method call" 
        "Retrieve and search chat history" 
        "Return multiple values" 
        "Reverse a string" 
        "Reverse words in a string" 
        "RIPEMD-160" 
        "Rock-paper-scissors" 
        "Roman numerals/Decode" 
        "Roman numerals/Encode" 
        "Roots of a function" 
        "Roots of a quadratic function" 
        "Roots of unity" 
        "Rosetta Code/Count examples" 
        "Rosetta Code/Find bare lang tags" 
        "Rosetta Code/Find unimplemented tasks" 
        "Rosetta Code/Fix code tags" 
        "Rosetta Code/Rank languages by popularity" 
        "Rot-13" 
        "RPG Attributes Generator" 
        "RSA code" 
        "Run-length encoding" 
        "Runge-Kutta method" 
        "Runtime evaluation" 
        "Runtime evaluation/In an environment" 
        "S-Expressions" 
        "Safe addition" 
        "Safe primes and unsafe primes" 
        "Sailors, coconuts and a monkey problem" 
        "Same Fringe" 
        "Scope modifiers" 
        "Scope/Function names and labels" 
        "Search a list" 
        "Search a list of records" 
        "Secure temporary file" 
        "SEDOLs" 
        "Self-describing numbers" 
        "Self-referential sequence" 
        "Semiprime" 
        "Semordnilap" 
        "Send an unknown method call" 
        "Send email" 
        "Sequence of non-squares" 
        "Sequence of primes by trial division" 
        "Sequence of primorial primes" 
        "Set" 
        "Set consolidation" 
        "Set of real numbers" 
        "Set puzzle" 
        "Seven-sided dice from five-sided dice" 
        "SHA-1" 
        "SHA-256" 
        "Shell one-liner" 
        "Shoelace formula for polygonal area" 
        "Short-circuit evaluation" 
        "Shortest common supersequence" 
        "Show the epoch" 
        "Sierpinski carpet" 
        "Sierpinski pentagon" 
        "Sierpinski triangle" 
        "Sierpinski triangle/Graphical" 
        "Sieve of Eratosthenes" 
        "Simple database" 
        "Simple windowed application" 
        "Simulate input/Keyboard" 
        "Simulate input/Mouse" 
        "Singleton" 
        "Singly-linked list/Element definition" 
        "Singly-linked list/Element insertion" 
        "Singly-linked list/Traversal" 
        "Sleep" 
        "Smith numbers" 
        "SOAP" 
        "Sockets" 
        "Sokoban" 
        "Solve a Hidato puzzle" 
        "Solve a Holy Knight's tour" 
        "Solve a Hopido puzzle" 
        "Solve a Numbrix puzzle" 
        "Solve the no connection puzzle" 
        "Sort a list of object identifiers" 
        "Sort an array of composite structures" 
        "Sort an integer array" 
        "Sort disjoint sublist" 
        "Sort stability" 
        "Sort three variables" 
        "Sort using a custom comparator" 
        "Sorting algorithms/Bead sort" 
        "Sorting algorithms/Bogosort" 
        "Sorting algorithms/Bubble sort" 
        "Sorting algorithms/Cocktail sort" 
        "Sorting algorithms/Comb sort" 
        "Sorting algorithms/Counting sort" 
        "Sorting algorithms/Gnome sort" 
        "Sorting algorithms/Heapsort" 
        "Sorting algorithms/Insertion sort" 
        "Sorting algorithms/Merge sort" 
        "Sorting algorithms/Pancake sort" 
        "Sorting algorithms/Permutation sort" 
        "Sorting algorithms/Quicksort" 
        "Sorting algorithms/Radix sort" 
        "Sorting algorithms/Selection sort" 
        "Sorting algorithms/Shell sort" 
        "Sorting algorithms/Sleep sort" 
        "Sorting algorithms/Stooge sort" 
        "Sorting algorithms/Strand sort" 
        "Soundex" 
        "Sparkline in unicode" 
        "Special characters" 
        "Special variables" 
        "Speech synthesis" 
        "Spelling of ordinal numbers" 
        "Spinning rod animation/Text" 
        "Spiral matrix" 
        "Split a character string based on change of character" 
        "SQL-based authentication" 
        "Square but not cube" 
        "Square-free integers" 
        "Stable marriage problem" 
        "Stack" 
        "Stack traces" 
        "Stair-climbing puzzle" 
        "Start from a main routine" 
        "State name puzzle" 
        "Statistics/Basic" 
        "Statistics/Normal distribution" 
        "Stem-and-leaf plot" 
        "Stern-Brocot sequence" 
        "Straddling checkerboard" 
        "Stream Merge" 
        "String append" 
        "String case" 
        "String comparison" 
        "String concatenation" 
        "String interpolation (included)" 
        "String length" 
        "String matching" 
        "String prepend" 
        "Strip a set of characters from a string" 
        "Strip block comments" 
        "Strip comments from a string" 
        "Strip control codes and extended characters from a string" 
        "Strip whitespace from a string/Top and tail" 
        "Subleq" 
        "Substring" 
        "Substring/Top and tail" 
        "Subtractive generator" 
        "Sudoku" 
        "Sum and product of an array" 
        "Sum and Product Puzzle" 
        "Sum digits of an integer" 
        "Sum multiples of 3 and 5" 
        "Sum of a series" 
        "Sum of squares" 
        "Sum to 100" 
        "Superellipse" 
        "Superpermutation minimisation" 
        "Sutherland-Hodgman polygon clipping" 
        "Symmetric difference" 
        "Synchronous concurrency" 
        "System time" 
        "Table creation/Postal addresses" 
        "Take notes on the command line" 
        "Taxicab numbers" 
        "Temperature conversion" 
        "Terminal control/Clear the screen" 
        "Terminal control/Coloured text" 
        "Terminal control/Cursor movement" 
        "Terminal control/Cursor positioning" 
        "Terminal control/Dimensions" 
        "Terminal control/Display an extended character" 
        "Terminal control/Hiding the cursor" 
        "Terminal control/Inverse video" 
        "Terminal control/Positional read" 
        "Terminal control/Preserve screen" 
        "Terminal control/Ringing the terminal bell" 
        "Terminal control/Unicode output" 
        "Ternary logic" 
        "Test a function" 
        "Test integerness" 
        "Text processing/1" 
        "Text processing/2" 
        "Text processing/Max licenses in use" 
        "Textonyms" 
        "The ISAAC Cipher" 
        "The Name Game" 
        "The Twelve Days of Christmas" 
        "Thiele's interpolation formula" 
        "Thue-Morse" 
        "Tic-tac-toe" 
        "Time a function" 
        "Tokenize a string" 
        "Tokenize a string with escaping" 
        "Top rank per group" 
        "Topic variable" 
        "Topological sort" 
        "Topswops" 
        "Total circles area" 
        "Towers of Hanoi" 
        "Trabb Pardo–Knuth algorithm" 
        "Tree traversal" 
        "Trigonometric functions" 
        "Truncatable primes" 
        "Truncate a file" 
        "Truth table" 
        "Twelve statements" 
        "Ulam spiral (for primes)" 
        "Unbias a random generator" 
        "Undefined values" 
        "Unicode strings" 
        "Unicode variable names" 
        "Universal Turing machine" 
        "Unix/ls" 
        "Update a configuration file" 
        "URL decoding" 
        "URL encoding" 
        "URL parser" 
        "Use another language to call a function" 
        "User input/Graphical" 
        "User input/Text" 
        "UTF-8 encode and decode" 
        "Validate International Securities Identification Number" 
        "Vampire number" 
        "Van der Corput sequence" 
        "Variable size/Get" 
        "Variable size/Set" 
        "Variable-length quantity" 
        "Variables" 
        "Variadic function" 
        "Vector products" 
        "Verify distribution uniformity/Chi-squared test" 
        "Verify distribution uniformity/Naive" 
        "Video display modes" 
        "Vigenère cipher" 
        "Vigenère cipher/Cryptanalysis" 
        "Visualize a tree" 
        "Vogel's approximation method" 
        "Voronoi diagram" 
        "Walk a directory/Non-recursively" 
        "Walk a directory/Recursively" 
        "Water collected between towers" 
        "Web scraping" 
        "Window creation" 
        "Window creation/X11" 
        "Window management" 
        "Wireworld" 
        "Word search" 
        "Word wrap" 
        "World Cup group stage" 
        "Write entire file" 
        "Write float arrays to a text file" 
        "Write language name in 3D ASCII" 
        "Write to Windows event log" 
        "Xiaolin Wu's line algorithm" 
        "XML/DOM serialization" 
        "XML/Input" 
        "XML/Output" 
        "XML/XPath" 
        "Y combinator" 
        "Yahoo! search interface" 
        "Yin and yang" 
        "Zebra puzzle" 
        "Zeckendorf arithmetic" 
        "Zeckendorf number representation" 
        "Zero to the zero power" 
        "Zhang-Suen thinning algorithm" 
        "Zig-zag matrix")
  "All languages in rosetta code currently.")



(defun rsta:urlify-term-for-search (term)
        (url-encode-url (s-replace " " "_" term)))

(defun rsta:urlify-code-list-buffer ()
  (interactive)
  (let ((sanitized-lines
         (string-join (-map (lambda (algos)
                              (s-replace-regexp "$" "\""
                                                (s-replace-regexp "^" "\""
                                                                  (url-encode-url (s-replace " " "_" algos)))) )
                            (s-split "\n" (buffer-to-string))) "\n")))
    (progn (erase-buffer)
           (insert sanitized-lines))))


(defun rsta-search ()
  (interactive)
  (let ((task (rsta:urlify-term-for-search (completing-read "task: " rsta-task-list)))
        (lang (rsta:urlify-term-for-search (completing-read "lang: " rsta-lang-list))))
    (eww (concat "http://rosettacode.org/wiki/" task "#" lang))))

(defun rsta ()
  (interactive)
  (progn
    (split-window-right)
    (rsta-search)))
