* breadth-first-search

* software-engineering/data-structures/graphs/search/BFS

Breadth-first search is one of the simplest algorithms for searching a
graph and the archetype for many important graph algorithms. Prim's
minimum-spanningtree algorithm (Section 23.2) and Dijkstra's
single-source shortest-paths algorithm (Section 24.3) use ideas similar
to those in breadth-first search.

Given a graph G = (V, E) and a distinguished source vertex s,
breadth-first search systematically explores the edges of G to
“discover” every vertex that is reachable from s. It computes the
distance (smallest number of edges) from s to each reachable vertex. It
also produces a “breadth-first tree” with root s that contains all
reachable vertices. For any vertex  reachable from s, the simple path
in the breadth-first tree from s to  corresponds to a “shortest path”
from s to  in G, that is, a path containing the smallest number of
edges. The algorithm works on both directed and undirected graphs.

Breadth-first search is so named because it expands the frontier between
discovered and undiscovered vertices uniformly across the breadth of the
frontier. That is, the algorithm discovers all vertices at distance k
from s before discovering any vertices at distance k C 1.

Cormen, Thomas H.; Leiserson, Charles E.; Rivest, Ronald L.; Stein,
Clifford. Introduction to Algorithms (Page 594). The MIT Press. Kindle
Edition.
