/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.anyline.swig.example;

public class libvxeJNI {
  public final static native long new_MySwigExample();
  public final static native void MySwigExample_setUp(long jarg1, MySwigExample jarg1_);
  public final static native void MySwigExample_run(long jarg1, MySwigExample jarg1_, long jarg2, long jarg3, MySwigResult jarg3_);
  public final static native void delete_MySwigExample(long jarg1);
  public final static native long new_MySwigResult__SWIG_0();
  public final static native long new_MySwigResult__SWIG_1(long jarg1, long jarg2);
  public final static native long MySwigResult_getThresholdedImage(long jarg1, MySwigResult jarg1_);
  public final static native long MySwigResult_getRegionOfInterest(long jarg1, MySwigResult jarg1_);
  public final static native void MySwigResult_setThresholdedImage(long jarg1, MySwigResult jarg1_, long jarg2);
  public final static native void MySwigResult_setRegionOfInterest(long jarg1, MySwigResult jarg1_, long jarg2);
  public final static native void delete_MySwigResult(long jarg1);
}
