/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.anyline.swig.example;

public class MySwigResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MySwigResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MySwigResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libvxeJNI.delete_MySwigResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MySwigResult() {
    this(libvxeJNI.new_MySwigResult__SWIG_0(), true);
  }

  public MySwigResult(SWIGTYPE_p_cv__Mat thresholdedImage, SWIGTYPE_p_cv__Rect regionOfInterest) {
    this(libvxeJNI.new_MySwigResult__SWIG_1(SWIGTYPE_p_cv__Mat.getCPtr(thresholdedImage), SWIGTYPE_p_cv__Rect.getCPtr(regionOfInterest)), true);
  }

  public org.opencv.core.Mat getThresholdedImage() {
     return new org.opencv.core.Mat(libvxeJNI.MySwigResult_getThresholdedImage(swigCPtr, this));
}

  public SWIGTYPE_p_cv__Rect getRegionOfInterest() {
    return new SWIGTYPE_p_cv__Rect(libvxeJNI.MySwigResult_getRegionOfInterest(swigCPtr, this), true);
  }

  public void setThresholdedImage(SWIGTYPE_p_cv__Mat thresholdedImage) {
    libvxeJNI.MySwigResult_setThresholdedImage(swigCPtr, this, SWIGTYPE_p_cv__Mat.getCPtr(thresholdedImage));
  }

  public void setRegionOfInterest(SWIGTYPE_p_cv__Rect regionOfInterest) {
    libvxeJNI.MySwigResult_setRegionOfInterest(swigCPtr, this, SWIGTYPE_p_cv__Rect.getCPtr(regionOfInterest));
  }

}
