/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.anyline.swig.example;

public class MySwigExample {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MySwigExample(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MySwigExample obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libvxeJNI.delete_MySwigExample(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MySwigExample() {
    this(libvxeJNI.new_MySwigExample(), true);
  }

  public void setUp() {
    libvxeJNI.MySwigExample_setUp(swigCPtr, this);
  }

  public void run(org.opencv.core.Mat inputImage, MySwigResult result) {
    libvxeJNI.MySwigExample_run(swigCPtr, this, inputImage.getNativeObjAddr(), MySwigResult.getCPtr(result), result);
  }

}
